name: GitHub Actions Test workflow
on: push

jobs:
  my-job:
    name: Job example
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: python --version
    - run: python .\XTest.py 